openapi: 3.0.3
info:
  title: ToDo API
  description: ToDoアプリケーションのAPI仕様
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /todos:
    get:
      summary: ToDoの一覧を取得
      responses:
        '200':
          description: 正常に取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: ToDoを新規作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{id}:
    get:
      summary: 特定のToDoを取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: 見つかりません
    put:
      summary: 特定のToDoを更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '200':
          description: 更新成功
    delete:
      summary: 特定のToDoを削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 削除成功
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          example: "abc123"
        title:
          type: string
          example: "買い物に行く"
        completed:
          type: boolean
          example: false
    NewTodo:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "宿題をやる"
        completed:
          type: boolean
          example: false
