name: Deploy Multi-Version OpenAPI Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'todo-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy specs to docs/
        run: |
          mkdir -p docs/todo-api
          cp -r todo-api/* docs/todo-api/

      - name: Commit updated docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update docs"
          git push
        continue-on-error: true
